### ISSUE TITLE
App stops when start scanning Android 10

### ISSUE THREAD

**Issue by maurerle** [marq24/UUID0xFD6FTracer#8]
App stops working when start scanning:

```
time: 1599463821407 
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference 
stacktrace: java.lang.RuntimeException: Unable to instantiate service com.emacberry.uuid0xfd6fscan.ScannerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference 	
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3940) 
	at android.app.ActivityThread.access$1500(ActivityThread.java:219) 	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875) 	
at android.os.Handler.dispatchMessage(Handler.java:107) 	at android.os.Looper.loop(Looper.java:214) 	
at android.app.ActivityThread.main(ActivityThread.java:7356) 	
at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference 	
at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:555) 	
at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:545) 	
at com.emacberry.uuid0xfd6fscan.Preferences.<init>(Preferences.java:23) 	
at com.emacberry.uuid0xfd6fscan.Preferences.getInstance(Preferences.java:15) 	
at com.emacberry.uuid0xfd6fscan.ScannerService.<init>(ScannerService.java:65) 	
at java.lang.Class.newInstance(Native Method) 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129) 	
at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3935) 	... 8 more
```
https://del.dog/ycocuxonus.txt

Xiaomi Redmi note 7
crDroid 6.8 +microg
Android 10

**Comment by marq24** [comment]
new build is there ;-)

**Comment by marq24** [comment]
aaaaand Thanks for reporting this!
